### PR TITLE
Handle promise rejections

### PR DESCRIPTION
**Pull request by rbayliss**
Hey there,
Thanks for this library.  We've been using it for a couple of years now in a small project.  Unfortunately, I just realized that it's not handling promise rejections at all though (at least, as far as I can tell).  It boils down to the `reject` case not being handled.  This PR is an attempt to handle them.

Minimal reproduction case:
```js
const EventEmitter = require('events-async');
const ee = new EventEmitter();

ee.on('setup', async function() {
    throw new Error('test');
})

ee.emit('setup').then(function() {
    console.log('ok');
}).catch(function() {
    console.log('err');
})
```
When I run this code in Node 10, I see an unhandled promise rejection.  After this PR, I see `err` printed, as expected.

### CODE REVIEW

**Comment by wesleytodd** [comment]
Hi @rbayliss!  I think you might be better off switching this our for [`emittery`](https://www.npmjs.com/package/emittery).  I considered updating this to be similar, but in the end I think it is probably better to just go with that package.  Is that an acceptable solution?

**Comment by rbayliss** [comment]
Thanks for the response. Yeah, I did look into `emittery`, but it would require some architectural changes we can't make yet, due to the [limitation of only allowing one argument to be passed](https://github.com/sindresorhus/emittery/blob/master/examples/eventdata.js#L15) as event data.

When we release a new major version of our package, we'll likely switch though.

**Comment by wesleytodd** [comment]
I will also add, with new language features there are better ways to do this (which emittery takes advantage of).  And also, in my experience there are great reasons *NOT* to use this approach at all.  Every time I thought using this was going to work for me I ended up pulling it out in favor of a more simple and clear approach.  It is why I stopped using this module, and even just a few days ago I started using emittery and a separate more simple implementation of the pattern.  I pulled out of that approach as well because it is more complicated than many alternatives.

**Comment by wesleytodd** [comment]
If you need to emit with multiple values you could always just wrap their `emit` and `on` methods to shim in support.  Convert to an array and back.

**Comment by wesleytodd** [comment]
All that said, I am willing to just give you commit and publish if you really do want to stick with this package 📦 😛

**Comment by rbayliss** [comment]
Yeah, I hear ya.  We're tied to the asynchronous emitter approach for the moment due to backward compatibility, but I can see the drawbacks of this pattern.

If you wouldn't mind committing/publishing, that'd be great.  It would save us some work that seems unnecessary to do before we do the refactor for the major version bump.

**Comment by wesleytodd** [comment]
So before you merge this (I gave you commit), could you make sure to update the travis to modern node versions?  And what is your npm user so I can also give you that access?

**Comment by rbayliss** [comment]
Will do.  NPM username is `rbayliss`.

**Comment by rbayliss** [comment]
Thanks a bunch, by the way!  Much appreciated.

**Comment by wesleytodd** [comment]
Awesome, and you will need to enable 2FA on your npm account to publish.

**Review by wesleytodd — CHANGES_REQUESTED** [review]
Add node 13 as well

**Comment by rbayliss** [comment]
Awesome.  I think I'm all set to merge and publish here.  Again, appreciate your help!

**Review by wesleytodd — APPROVED** [review]

**Pull request merged**
